github action ubuntu #2

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -35,8 +35,13 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y ninja-build \
-            qt6-base-dev qt6-tools-dev qt6-tools-dev-tools \
+            qt6-base-dev qt6-tools-full-dev \
             libgl1-mesa-dev libglu1-mesa-dev
+        # Verify lconvert installation
+        if [ ! -f /usr/lib/qt6/bin/lconvert ]; then
+          echo "Error: lconvert not found!"
+          exit 1
+        fi
         echo "CMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV
 
     ### macOS Dependencies
